// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7mq6Eefjgxkdg5dEweYxKPyCzUoHS0Jo',
    appId: '1:846524652631:web:fe413cb16dcc12e7861712',
    messagingSenderId: '846524652631',
    projectId: 'login-app-d5d06',
    authDomain: 'login-app-d5d06.firebaseapp.com',
    storageBucket: 'login-app-d5d06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa0ey19pSeTj_Vbx5FvbJN7p9gW_Bm96k',
    appId: '1:846524652631:android:040cadd515394c25861712',
    messagingSenderId: '846524652631',
    projectId: 'login-app-d5d06',
    storageBucket: 'login-app-d5d06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjcupvHbsSbKhH39KAMe3czs5qE15YmUY',
    appId: '1:846524652631:ios:66b6d84667344b6d861712',
    messagingSenderId: '846524652631',
    projectId: 'login-app-d5d06',
    storageBucket: 'login-app-d5d06.appspot.com',
    androidClientId: '846524652631-3odr2eo4429s76gfn82fsvcm5hoeut9v.apps.googleusercontent.com',
    iosClientId: '846524652631-em75q2ee3l4nlu7sjs333b5k7rbq6dg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjcupvHbsSbKhH39KAMe3czs5qE15YmUY',
    appId: '1:846524652631:ios:66b6d84667344b6d861712',
    messagingSenderId: '846524652631',
    projectId: 'login-app-d5d06',
    storageBucket: 'login-app-d5d06.appspot.com',
    androidClientId: '846524652631-3odr2eo4429s76gfn82fsvcm5hoeut9v.apps.googleusercontent.com',
    iosClientId: '846524652631-em75q2ee3l4nlu7sjs333b5k7rbq6dg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7mq6Eefjgxkdg5dEweYxKPyCzUoHS0Jo',
    appId: '1:846524652631:web:41b9a3eb10936b01861712',
    messagingSenderId: '846524652631',
    projectId: 'login-app-d5d06',
    authDomain: 'login-app-d5d06.firebaseapp.com',
    storageBucket: 'login-app-d5d06.appspot.com',
  );

}